version: "3.8"
services:
    wispr:
        build: .
        ports:
            - "9090:9090"
        env_file:
            - .env
        volumes:
            - ./public:/usr/src/app/public
            - ./views:/usr/src/app/views
            - ./certs:/usr/src/app/certs
        restart: unless-stopped
