version: '3.8'
services:
  wispr:
    build: .
    ports:
      - "9080:8080"
      - "9443:8443"
    env_file:
      - .env
    volumes:
      - ./public:/usr/src/app/public
      - ./views:/usr/src/app/views
    restart: unless-stopped
